### ISSUE TITLE
Add compute capability check

### ISSUE THREAD

**Issue by drakorg** [rbonghi/jetson_stats#119]
**Is your feature request related to a problem? Please describe.**
The other day I compiled opencv from source specifying a wrong compute capability, which of course made opencv unable to use the cuda accelerated libraries. However, when I was looking for some information on what the problem was, I recurred to this great tool for a diagnostic and it told that everything was fine: it stated that opencv was present, and that it had been compiled with cuda support, when despite all that being true, cuda support for opencv was still unavailable in my installation.

**Describe the solution you'd like**
It would be nice if jtop could add an extra check (in the info tab) to see if the compute capability of the compiled opencv does indeed match the compute capability of the running host. If it does, great, it could be print in green, and if it doesnt, in read. That way one could use jtop to quickly check if everything is fine with the opencv installation.

**Describe alternatives you've considered**

**Additional context**

Thank you.
Best regards.

**Comment by rbonghi** [comment]
Hi @drakorg 

I am replying to your issue after ages!
I was looking to read this information, but there are too many variables to know that seems impossible.

By the way, instead of jtop (It's made to monitor the Jetson and not show the capabilities for each software), I think it is better to make a script to check the NVIDIA capabilities for the OpenCV libraries.

I close this issue,
but feel free to reopen it
